import type { ServerStats } from "./types";

// PLACEHOLDER: fake hosts and readings until Chad picks the real ones (design section 18, question 7). The row labels
// adapt the DCS ENG labels lightly; docs/pages/eng.md maps each one to the engine parameter it replaces.
export const SERVER_STATS: ServerStats = {
  hosts: [
    { header: "LEFT NAS", name: "nas-01 (storage)" },
    { header: "RIGHT NUC", name: "nuc-02 (compute)" },
  ],
  rows: [
    {
      metric: "inletTemp",
      label: "INLET TEMP",
      name: "Case inlet temperature",
      unit: "°C",
      decimals: 0,
      suffix: "",
    },
    {
      metric: "cpu",
      label: "CPU %",
      name: "CPU load",
      unit: "%",
      decimals: 0,
      suffix: "",
    },
    {
      metric: "ram",
      label: "RAM %",
      name: "Memory used",
      unit: "%",
      decimals: 0,
      suffix: "",
    },
    {
      metric: "cpuTemp",
      label: "CPU TEMP",
      name: "CPU temperature",
      unit: "°C",
      decimals: 0,
      suffix: "",
    },
    {
      metric: "power",
      label: "PWR DRAW",
      name: "Power draw",
      unit: "W",
      decimals: 0,
      suffix: "",
    },
    {
      metric: "fan",
      label: "FAN RPM",
      name: "Fan speed",
      unit: "rpm",
      decimals: 0,
      suffix: "",
    },
    {
      metric: "memPressure",
      label: "MEM PRESS",
      name: "Memory pressure (PSI)",
      unit: "%",
      decimals: 1,
      suffix: "",
    },
    {
      metric: "throughput",
      label: "THRUPUT",
      name: "Network throughput",
      unit: "Mb/s",
      decimals: 0,
      suffix: "",
    },
    {
      metric: "jitter",
      label: "JITTER",
      name: "Network jitter",
      unit: "ms",
      decimals: 1,
      suffix: "",
    },
    {
      metric: "diskTemp",
      label: "DISK TEMP",
      name: "Disk temperature",
      unit: "°C",
      decimals: 0,
      suffix: "",
    },
    {
      metric: "loadAvg",
      label: "LOAD AVG",
      name: "Load average (1 minute)",
      unit: "",
      decimals: 2,
      suffix: "",
    },
    {
      metric: "disk",
      label: "DISK %",
      name: "Disk used",
      unit: "%",
      decimals: 0,
      suffix: "",
    },
    {
      metric: "uptime",
      label: "UPTIME",
      name: "Uptime",
      unit: "days",
      decimals: 0,
      suffix: "D",
    },
  ],
  baseline: {
    hosts: [
      {
        inletTemp: 24,
        cpu: 18,
        ram: 62,
        cpuTemp: 46,
        power: 38,
        fan: 820,
        memPressure: 0.4,
        throughput: 312,
        jitter: 0.4,
        diskTemp: 37,
        loadAvg: 0.72,
        disk: 64,
        uptime: 41,
      },
      {
        inletTemp: 27,
        cpu: 47,
        ram: 71,
        cpuTemp: 63,
        power: 72,
        fan: 1460,
        memPressure: 2.1,
        throughput: 86,
        jitter: 0.9,
        diskTemp: 41,
        loadAvg: 3.4,
        disk: 23,
        uptime: 12,
      },
    ],
  },
};
